### PR TITLE
[homework #2] - HTML by Nicolás Roberto

### PR DESCRIPTION
**Pull request by nicolasroberto**
Changed folder name nr-02-html to 02-html.

### CODE REVIEW

**Review by solvd-mmelnyk — CHANGES_REQUESTED** [review]
@nicolasroberto please remove old folder: `nr-02-html`

**Comment by nicolasroberto** [comment]
> @nicolasroberto please remove old folder: `nr-02-html`

I just need to delete it from my directory? Because i it doesn't let me commit the same folder again.

**Comment by solvd-mmelnyk** [comment]
> > @nicolasroberto please remove old folder: `nr-02-html`
> 
> I just need to delete it from my directory? Because i it doesn't let me commit the same folder again.

yes, you should delete it from your directory

**Comment by nicolasroberto** [comment]
> yes, you should delete it from your directory

Great, i deleted it already.

**Review by solvd-mmelnyk — APPROVED** [review]

**Pull request merged**
