### PR TITLE
[homework #12] - data-structures-and-algorithms by Emiliano Acerbi

### PR DESCRIPTION
**Pull request by emiacerbi**
Hi @VitalikMelnyk . This is my first iteration of the data structures and algorithms task. I will update it with the rest of the methods.

### CODE REVIEW

**Comment by solvd-mmelnyk** [comment]
@emiacerbi hey! are you going to add more code or is this final version?

**Comment by emiacerbi** [comment]
Hi! I added the results. Please let me know if there's anything to fix

**Comment by VitalikMelnyk** [comment]
Well Done @emiacerbi!

**Review by VitalikMelnyk — APPROVED** [review]

**Comment by emiacerbi** [comment]
Thank you!

**Pull request merged**
