### PR TITLE
[homework #13] - environment-and-preprocessors  by German Macchia

### PR DESCRIPTION
**Pull request by GermanMacchia**

### CODE REVIEW

**Comment by VitalikMelnyk** [comment]
My notes: 
1. Create README.md with step-by-step instructions on how to run our app.
2. See responsive mode and fix mobile styles.
Screenshot 2022-08-15 at 19 50 10

**Comment by GermanMacchia** [comment]
> @GermanMacchia, my notes:
> 
>     1. Create README.md with step-by-step instructions on how to run our app.
> 
>     2. See responsive mode and fix mobile styles.


Hey @VitalikMelnyk !
Sure! I will push an updated version soon.
Thanks!

**Comment by GermanMacchia** [comment]
Hi @VitalikMelnyk!
I made a new push to homework, 
hope everything is allright!
Please let me know for any detail.

Thanks in advance!

**Comment by VitalikMelnyk** [comment]
Looks good, well done @GermanMacchia.

**Review by VitalikMelnyk — APPROVED** [review]

**Comment by GermanMacchia** [comment]
> Looks good, well done @GermanMacchia.
> 

Thank you Vitalli!

**Pull request merged**
