### PR TITLE
[homework #10] - Js-DOM by Abraham Trenyan

### PR DESCRIPTION
**Pull request by AbrahamTrenyan**
Hey Vitali, I haven't finished with this one, but I created PR so you can see how I'm doing anyways.
My main issue is that I can't handle disallowing multiple selections of cells.
I'm going to try to solve this on the weekend, but this is my progress till now.

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
It is not working as needed. 

If you click on cell without holding shift button , this cell should be selected and all previously selected cells should not be selected.

If you click on cell with holding shift button , this cell should be selected and all previously selected cells should stay selected

**Comment by AbrahamTrenyan** [comment]
> 
Hey Ilya, thanks for the comments!
I fixed it, now it works fine, only allows one selection without holding the shift key.
I'm still trying to add the advanced feature to allow multiple selections with the shift key, but if you think it's fine you can merge this.

**Comment by AbrahamTrenyan** [comment]
> > 
> 
> Hey Ilya, thanks for the comments! I fixed it, now it works fine, only allows one selection without holding the shift key. I'm still trying to add the advanced feature to allow multiple selections with the shift key, but if you think it's fine you can merge this.

I added advanced feature too now!

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
