### PR TITLE
[homework #12] - Data structures and algorithms by Nicolás Roberto

### PR DESCRIPTION
**Pull request by nicolasroberto**
I still need to finish the .log file part.

### CODE REVIEW

**Review by solvd-mmelnyk — CHANGES_REQUESTED** [review]
@nicolasroberto are you going to add something to this homework?
why do I see changes for 11-js-advanced-3/codewars.js in homework #12?
please make sure that you pushed correct files!

**Comment by nicolasroberto** [comment]
> @nicolasroberto are you going to add something to this homework? why do I see changes for 11-js-advanced-3/codewars.js in homework #12? please make sure that you pushed correct files!

I'm trying to make the .log file work but i can't push the console in there.
I think i might change the logic to work only in node.
I don't understand why my 11 homework is there. Should i delete it?

**Comment by solvd-mmelnyk** [comment]
> > @nicolasroberto are you going to add something to this homework? why do I see changes for 11-js-advanced-3/codewars.js in homework #12? please make sure that you pushed correct files!
> 
> I'm trying to make the .log file work but i can't push the console in there. I think i might change the logic to work only in node. I don't understand why my 11 homework is there. Should i delete it?

looks like you created this branch from not main but from branch for 11 homework
please make sure that you updated this branch from latest main

**Comment by nicolasroberto** [comment]
> > > @nicolasroberto are you going to add something to this homework? why do I see changes for 11-js-advanced-3/codewars.js in homework #12? please make sure that you pushed correct files!
> > 
> > 
> > I'm trying to make the .log file work but i can't push the console in there. I think i might change the logic to work only in node. I don't understand why my 11 homework is there. Should i delete it?
> 
> looks like you created this branch from not main but from branch for 11 homework please make sure that you updated this branch from latest main

Thanks!

**Pull request closed without merging**
