### PR TITLE
[homework #7] - Js basics 2 by Julian Oviedo

### PR DESCRIPTION
**Pull request by JulianOviedo**

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
Looks good as for me!

1. Need to create folder for this HW
2. You file with solutions do not have .js extension
3. Is it all tasks that you want to submit?

**Comment by JulianOviedo** [comment]
> Se ve bien en cuanto a mí!
> 
> 1. Necesidad de crear una carpeta para este HW
> 2. Tu archivo con soluciones no tiene extensión .js
> 3. ¿Son todas las tareas que desea enviar?

1/2 - Done. Sorry, my bad. I just forgot to do it before the PR
3- I just completed the required katas. I'll try to do some of the optional-advanced by tomorrow and set the review again.

Thank you Ilya !

**Comment by ilya-ischenko** [comment]
> > Se ve bien en cuanto a mí!
> > 
> > 1. Necesidad de crear una carpeta para este HW
> > 2. Tu archivo con soluciones no tiene extensión .js
> > 3. ¿Son todas las tareas que desea enviar?
> 
> 1/2 - Done. Sorry, my bad. I just forgot to do it before the PR 3- I just completed the required katas. I'll try to do some of the optional-advanced by tomorrow and set the review again.
> 
> Thank you Ilya !

How it is going?
Do you want to merge it?

**Comment by JulianOviedo** [comment]
> 

Yes Ilya, please. I prefer to dedicate the time in the others tasks.

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved

**Pull request merged**
