### PR TITLE
[homework #13] - environment-and-preprocessors by  Brisa Rojas

### PR DESCRIPTION
**Pull request by bytheseaside**

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
Does it make compressed css file?
Change script names due to required it the task sass_build -> build, sass_watch -> start

**Comment by bytheseaside** [comment]
> Does it make compressed css file?

No, I'm still working on this homework. Will update it 

> Change script names due to required it the task sass_build -> build, sass_watch -> start

Yes, sorry about that

**Comment by ilya-ischenko** [comment]
> > Does it make compressed css file?
> 
> No, I'm still working on this homework. Will update it Edit: I already committed the modification for build to make compressed css file (I assumed we need "normal"+compressed css, is it correct or should I only make a compressed css file?)
> 
> > Change script names due to required it the task sass_build -> build, sass_watch -> start
> 
> Yes, sorry about that

For the "dev" mode we need "normal" css file, for the "build" mode we need compressed css file

**Review by ilya-ischenko — COMMENTED** [review]
1. I can not build app - https://postimg.cc/sMtmfkFH
2. For future: folder names should start with lower case letter

**Comment by bytheseaside** [comment]
I modified `build` so now it compiles a css(styles.css) and compressed css (styles.min.css) file both in same folder inside styles/css

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
