### PR TITLE
[Homework #18] - Hooks by Brisa Rojas

### PR DESCRIPTION
**Pull request by bytheseaside**
Hi Ilya, here's my homework 18
Let me know if there's something I can improve

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
Let's try to improve project structure.

1. Make dedicated styles for each component instead of use "App.css" for all project styles. You can add folder for each component where you can store js and css file. Folder name must be the same as component name. AddButton for example.

2. Create assets folder and move all images/icons which you use in this folder

**Review by ilya-ischenko — COMMENTED** [review]
I am sorry
Seems that I confused you.
Components should be in the "components" folder. 
component (folder)
 - AddButton (folder)
     - AddButton.js
     - styles.css

Also you can create "styles" folder for the global styles and move you index.css and App.css to this folder

**Comment by bytheseaside** [comment]
Oh, sorry I'll fix the component folder issue and make folder for the other 2 css files

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
