### PR TITLE
[homework #10] - js-dom by Julian Oviedo

### PR DESCRIPTION
**Pull request by JulianOviedo**
Hey @ilya-ischenko ! Let me know how it's looks like this hw. 

Thank you !

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
Looks good as for me!

Review task again, please. 
`Active row and column should be highlighted with light blue color`

**Comment by JulianOviedo** [comment]
> 

fixed, my bad.

**Comment by JulianOviedo** [comment]
> Looks good as for me!
> 
> Review task again, please. `Active row and column should be highlighted with light blue color`

fixed ! My bad, sorry.

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved

**Pull request merged**
