### PR TITLE
[Homework #20] - routing-redux by German Macchia

### PR DESCRIPTION
**Pull request by GermanMacchia**
@VitalikMelnyk ,
This is my first approach to homework nº20.
Thanks

### CODE REVIEW

**Comment by VitalikMelnyk** [comment]
Please, review my notes and fix conflicts.
Thanks.

**Comment by GermanMacchia** [comment]
hey @VitalikMelnyk,
thanks for the suggestions.
Made some changes according your review.
Hope everything looks better.
many thanks!

**Comment by VitalikMelnyk** [comment]
Hello @GermanMacchia.
Please, resolve git conflicts.

**Comment by GermanMacchia** [comment]
> 

Done!

**Comment by GermanMacchia** [comment]
> > 
> 
> Done!

**Pull request closed without merging**
